name: Create a new tag, and push it
description: ""

inputs:
  tag:
    description: Tag to push
    required: true
  app-client-id:
    required: false
    description: ""
  app-private-key:
    required: false
    description: ""

runs:
  using: node24
  main: dist/index.js
