name: pr

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:

  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ secrets.BOT_APP_CLIENT_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      -
        uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token || github.token }}
      -
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: npm
          cache-dependency-path: package-lock.json
      -
        run: npm ci
      -
        name: Lint source code
        run: npm run lint
      -
        name: Run tests
        run: npm run test
      -
        name: Repack outputs
        run: |
          npm run build
          npm run pack
      -
        name: Run auto-doc
        uses: tj-actions/auto-doc@v3
      -
        name: Check for changes
        id: detect-changes
        uses: tj-actions/verify-changed-files@v20
      -
        name: Commit changes if detected
        if: ${{ steps.detect-changes.outputs.files_changed == 'true' }}
        uses: planetscale/ghcommit-action@v0.2.20
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token || github.token }}
        with:
          commit_message: "generated changes"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref }}
